### PR TITLE
Disable Chrome web security

### PR DESCRIPTION
**Pull request by wiled**
Without this change when running all tests together using `yarn
cypress:run` these errors occur:

"blocked a frame with origin [] from accessing a cross-origin frame"

See:
https://github.com/cypress-io/cypress/issues/1951
https://stackoverflow.com/q/56046632

### CODE REVIEW

**Review by martinmcneela — CHANGES_REQUESTED** [review]
I get the tests failing when running this branch, but they pass when running the main branch.

**Comment by wiled** [comment]
I needed this when running all of the tests on my scenario 5 branch.   Must have been using either Chrome 87 or Electron 87.

**Comment by zac-robinson** [comment]
So these tests work the same for me if I am on the main branch or if I am on this branch. Both run and pass no problem

**Comment by martinmcneela** [comment]
I guess we should wait see how it runs on GH actions?

**Comment by Hazz223** [comment]
It doesn't @martinmcneela - tests fail randomly (though, each failure is consistent) each run. I'm having a similar time locally too. 
I'm now looking at how we can stabilise these tests. Will produce a PR and see what folk think

**Comment by martinmcneela** [comment]
@wiled is this PR still needed given the work @Hazz223 has bone in https://github.com/edozo/cypress_tests/pull/10?

**Comment by wiled** [comment]
> @wiled is this PR still needed given the work @Hazz223 has bone in #10?

I'll test that out after it's merged and if it works for me locally this can close

**Comment by wiled** [comment]
Or it can close now as I pressed the wrong button

**Pull request closed without merging**
